/*
 * Woleet API
 * Welcome to **Woleet API reference documentation**.<br> It is highly recommanded to read the chapters **[introducing Woleet API concepts](https://doc.woleet.io/v1.5.1/reference)** before reading this documentation. 
 *
 * OpenAPI spec version: 1.5.2
 * Contact: contact@woleet.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.woleet.api.client;

import io.woleet.api.ApiException;
import io.woleet.api.client.model.Receipt;
import io.woleet.api.client.model.ReceiptVerificationStatus;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ReceiptApi
 */
@Ignore
public class ReceiptApiTest {

    private final ReceiptApi api = new ReceiptApi();

    
    /**
     * Get the proof receipt of an anchor (OpenTimestamps proof format).
     *
     * Use this operation to retrieve the OpenTimestamps proof receipt associated to a given anchor. This is a publicly accessible endpoint: authentication is not required to retrieve a proof receipt (but the anchor identifier need to be known). 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getOTSReceiptTest() throws ApiException {
        String anchorid = null;
        String response = api.getOTSReceipt(anchorid);

        // TODO: test validations
    }
    
    /**
     * Get the proof receipt of an anchor (Chainpoint proof format).
     *
     * Use this operation to retrieve the Chainpoint proof receipt associated to a given anchor. This is a publicly accessible endpoint: authentication is not required to retrieve a proof receipt (but the anchor identifier need to be known). 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getReceiptTest() throws ApiException {
        String anchorid = null;
        Receipt response = api.getReceipt(anchorid);

        // TODO: test validations
    }
    
    /**
     * Verify a proof receipt.
     *
     * Use this operation to verify a Chainpoint proof receipt and get the timestamp of the proof.&lt;br&gt; For proof of signature receipts including an identity URL, this operation also verify and returns information about the signee&#39;s identity.&lt;br&gt; This is a publicly accessible endpoint: authentication is not required to verify a proof receipt. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void verifyReceiptTest() throws ApiException {
        Receipt receipt = null;
        ReceiptVerificationStatus response = api.verifyReceipt(receipt);

        // TODO: test validations
    }
    
}
