/*
 * Woleet API
 * Welcome to **Woleet API reference documentation**.<br> It is highly recommanded to read the chapters **[introducing Woleet API concepts](https://doc.woleet.io/v1.5.1/reference)** before reading this documentation. 
 *
 * OpenAPI spec version: 1.5.2
 * Contact: contact@woleet.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.woleet.api.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * AuthorizedSignee
 */

public class AuthorizedSignee {
  @SerializedName("pubKey")
  private String pubKey = null;

  @SerializedName("required")
  private Boolean required = null;

  public AuthorizedSignee pubKey(String pubKey) {
    this.pubKey = pubKey;
    return this;
  }

   /**
   * The public key of the authorized signee.
   * @return pubKey
  **/
  @ApiModelProperty(value = "The public key of the authorized signee.")
  public String getPubKey() {
    return pubKey;
  }

  public void setPubKey(String pubKey) {
    this.pubKey = pubKey;
  }

  public AuthorizedSignee required(Boolean required) {
    this.required = required;
    return this;
  }

   /**
   * &#x60;true&#x60; if this signee&#39;s signature is mandatory.&lt;br&gt; This property is informative, it is not used by the platform. 
   * @return required
  **/
  @ApiModelProperty(value = "`true` if this signee's signature is mandatory.<br> This property is informative, it is not used by the platform. ")
  public Boolean isRequired() {
    return required;
  }

  public void setRequired(Boolean required) {
    this.required = required;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AuthorizedSignee authorizedSignee = (AuthorizedSignee) o;
    return Objects.equals(this.pubKey, authorizedSignee.pubKey) &&
        Objects.equals(this.required, authorizedSignee.required);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pubKey, required);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AuthorizedSignee {\n");
    
    sb.append("    pubKey: ").append(toIndentedString(pubKey)).append("\n");
    sb.append("    required: ").append(toIndentedString(required)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

