/*
 * Woleet API
 * Welcome to **Woleet API reference documentation**.<br> It is highly recommanded to read the chapters **[introducing Woleet API concepts](https://doc.woleet.io/reference)** before reading this documentation. 
 *
 * The version of the OpenAPI document: 1.13.0
 * Contact: contact@woleet.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.woleet.api.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Credits
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class Credits {
  public static final String SERIALIZED_NAME_CREDITS = "credits";
  @SerializedName(SERIALIZED_NAME_CREDITS)
  private Integer credits;

  public static final String SERIALIZED_NAME_SEAL_CREDITS = "sealCredits";
  @SerializedName(SERIALIZED_NAME_SEAL_CREDITS)
  private Integer sealCredits;

  public static final String SERIALIZED_NAME_SIGN_CREDITS = "signCredits";
  @SerializedName(SERIALIZED_NAME_SIGN_CREDITS)
  private Integer signCredits;

  public static final String SERIALIZED_NAME_SIGNATURE_REQUEST_CREDITS = "signatureRequestCredits";
  @SerializedName(SERIALIZED_NAME_SIGNATURE_REQUEST_CREDITS)
  private Integer signatureRequestCredits;

  public static final String SERIALIZED_NAME_SMS_CREDITS = "smsCredits";
  @SerializedName(SERIALIZED_NAME_SMS_CREDITS)
  private Integer smsCredits;


  public Credits credits(Integer credits) {
    
    this.credits = credits;
    return this;
  }

   /**
   * The remaining number of timestamp credits of the authenticated user&#39;s account.
   * @return credits
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1234", value = "The remaining number of timestamp credits of the authenticated user's account.")

  public Integer getCredits() {
    return credits;
  }


  public void setCredits(Integer credits) {
    this.credits = credits;
  }


  public Credits sealCredits(Integer sealCredits) {
    
    this.sealCredits = sealCredits;
    return this;
  }

   /**
   * The remaining number of seal credits of the authenticated user&#39;s account.
   * @return sealCredits
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1234", value = "The remaining number of seal credits of the authenticated user's account.")

  public Integer getSealCredits() {
    return sealCredits;
  }


  public void setSealCredits(Integer sealCredits) {
    this.sealCredits = sealCredits;
  }


  public Credits signCredits(Integer signCredits) {
    
    this.signCredits = signCredits;
    return this;
  }

   /**
   * The remaining number of signature credits of the authenticated user&#39;s account.
   * @return signCredits
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1234", value = "The remaining number of signature credits of the authenticated user's account.")

  public Integer getSignCredits() {
    return signCredits;
  }


  public void setSignCredits(Integer signCredits) {
    this.signCredits = signCredits;
  }


  public Credits signatureRequestCredits(Integer signatureRequestCredits) {
    
    this.signatureRequestCredits = signatureRequestCredits;
    return this;
  }

   /**
   * The remaining number of signature request credits of the authenticated user&#39;s account.
   * @return signatureRequestCredits
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1234", value = "The remaining number of signature request credits of the authenticated user's account.")

  public Integer getSignatureRequestCredits() {
    return signatureRequestCredits;
  }


  public void setSignatureRequestCredits(Integer signatureRequestCredits) {
    this.signatureRequestCredits = signatureRequestCredits;
  }


  public Credits smsCredits(Integer smsCredits) {
    
    this.smsCredits = smsCredits;
    return this;
  }

   /**
   * The remaining number of SMS credits of the authenticated user&#39;s account.
   * @return smsCredits
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1234", value = "The remaining number of SMS credits of the authenticated user's account.")

  public Integer getSmsCredits() {
    return smsCredits;
  }


  public void setSmsCredits(Integer smsCredits) {
    this.smsCredits = smsCredits;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Credits credits = (Credits) o;
    return Objects.equals(this.credits, credits.credits) &&
        Objects.equals(this.sealCredits, credits.sealCredits) &&
        Objects.equals(this.signCredits, credits.signCredits) &&
        Objects.equals(this.signatureRequestCredits, credits.signatureRequestCredits) &&
        Objects.equals(this.smsCredits, credits.smsCredits);
  }

  @Override
  public int hashCode() {
    return Objects.hash(credits, sealCredits, signCredits, signatureRequestCredits, smsCredits);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Credits {\n");
    sb.append("    credits: ").append(toIndentedString(credits)).append("\n");
    sb.append("    sealCredits: ").append(toIndentedString(sealCredits)).append("\n");
    sb.append("    signCredits: ").append(toIndentedString(signCredits)).append("\n");
    sb.append("    signatureRequestCredits: ").append(toIndentedString(signatureRequestCredits)).append("\n");
    sb.append("    smsCredits: ").append(toIndentedString(smsCredits)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

