/*
 * Woleet API
 * Welcome to **Woleet API reference documentation**.<br> It is highly recommanded to read the chapters **[introducing Woleet API concepts](https://doc.woleet.io/v1.5.1/reference)** before reading this documentation. 
 *
 * OpenAPI spec version: 1.5.3
 * Contact: contact@woleet.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.woleet.api.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * For proof of signature receipts only. The anchored signature.
 */
@ApiModel(description = "For proof of signature receipts only. The anchored signature.")

public class ReceiptSignature {
  public static final String SERIALIZED_NAME_SIGNED_HASH = "signedHash";
  @SerializedName(SERIALIZED_NAME_SIGNED_HASH)
  private String signedHash;

  public static final String SERIALIZED_NAME_PUB_KEY = "pubKey";
  @SerializedName(SERIALIZED_NAME_PUB_KEY)
  private String pubKey;

  public static final String SERIALIZED_NAME_SIGNATURE = "signature";
  @SerializedName(SERIALIZED_NAME_SIGNATURE)
  private String signature;

  public static final String SERIALIZED_NAME_IDENTITY_U_R_L = "identityURL";
  @SerializedName(SERIALIZED_NAME_IDENTITY_U_R_L)
  private String identityURL;

  public ReceiptSignature signedHash(String signedHash) {
    this.signedHash = signedHash;
    return this;
  }

   /**
   * SHA256 hash (ie. the fingerprint) of the original signed data.
   * @return signedHash
  **/
  @ApiModelProperty(value = "SHA256 hash (ie. the fingerprint) of the original signed data.")
  public String getSignedHash() {
    return signedHash;
  }

  public void setSignedHash(String signedHash) {
    this.signedHash = signedHash;
  }

  public ReceiptSignature pubKey(String pubKey) {
    this.pubKey = pubKey;
    return this;
  }

   /**
   * Public key of the signee.
   * @return pubKey
  **/
  @ApiModelProperty(value = "Public key of the signee.")
  public String getPubKey() {
    return pubKey;
  }

  public void setPubKey(String pubKey) {
    this.pubKey = pubKey;
  }

  public ReceiptSignature signature(String signature) {
    this.signature = signature;
    return this;
  }

   /**
   * Signature of the &#x60;signedHash&#x60; property using the public key stored in the &#x60;pubKey&#x60; property.
   * @return signature
  **/
  @ApiModelProperty(value = "Signature of the `signedHash` property using the public key stored in the `pubKey` property.")
  public String getSignature() {
    return signature;
  }

  public void setSignature(String signature) {
    this.signature = signature;
  }

  public ReceiptSignature identityURL(String identityURL) {
    this.identityURL = identityURL;
    return this;
  }

   /**
   * Web hook to use to verify the signee&#39;s identity.
   * @return identityURL
  **/
  @ApiModelProperty(value = "Web hook to use to verify the signee's identity.")
  public String getIdentityURL() {
    return identityURL;
  }

  public void setIdentityURL(String identityURL) {
    this.identityURL = identityURL;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReceiptSignature receiptSignature = (ReceiptSignature) o;
    return Objects.equals(this.signedHash, receiptSignature.signedHash) &&
        Objects.equals(this.pubKey, receiptSignature.pubKey) &&
        Objects.equals(this.signature, receiptSignature.signature) &&
        Objects.equals(this.identityURL, receiptSignature.identityURL);
  }

  @Override
  public int hashCode() {
    return Objects.hash(signedHash, pubKey, signature, identityURL);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReceiptSignature {\n");
    
    sb.append("    signedHash: ").append(toIndentedString(signedHash)).append("\n");
    sb.append("    pubKey: ").append(toIndentedString(pubKey)).append("\n");
    sb.append("    signature: ").append(toIndentedString(signature)).append("\n");
    sb.append("    identityURL: ").append(toIndentedString(identityURL)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

