/*
 * Woleet API
 * Welcome to **Woleet API reference documentation**.<br> It is highly recommanded to read the chapters **[introducing Woleet API concepts](https://doc.woleet.io/v1.5.1/reference)** before reading this documentation. 
 *
 * OpenAPI spec version: 1.5.1
 * Contact: contact@woleet.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.woleet.api.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * SignatureRequestSign
 */

public class SignatureRequestSign {
  @SerializedName("signature")
  private String signature = null;

  @SerializedName("pubKey")
  private String pubKey = null;

  public SignatureRequestSign signature(String signature) {
    this.signature = signature;
    return this;
  }

   /**
   * Signature of the &#x60;hashToSign&#x60; property of the signature request using the public key stored in the &#x60;pubKey&#x60; property. 
   * @return signature
  **/
  @ApiModelProperty(value = "Signature of the `hashToSign` property of the signature request using the public key stored in the `pubKey` property. ")
  public String getSignature() {
    return signature;
  }

  public void setSignature(String signature) {
    this.signature = signature;
  }

  public SignatureRequestSign pubKey(String pubKey) {
    this.pubKey = pubKey;
    return this;
  }

   /**
   * Public key of the signee. 
   * @return pubKey
  **/
  @ApiModelProperty(value = "Public key of the signee. ")
  public String getPubKey() {
    return pubKey;
  }

  public void setPubKey(String pubKey) {
    this.pubKey = pubKey;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SignatureRequestSign signatureRequestSign = (SignatureRequestSign) o;
    return Objects.equals(this.signature, signatureRequestSign.signature) &&
        Objects.equals(this.pubKey, signatureRequestSign.pubKey);
  }

  @Override
  public int hashCode() {
    return Objects.hash(signature, pubKey);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SignatureRequestSign {\n");
    
    sb.append("    signature: ").append(toIndentedString(signature)).append("\n");
    sb.append("    pubKey: ").append(toIndentedString(pubKey)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

