/*
 * Woleet API
 * Welcome to **Woleet API reference documentation**.<br> It is highly recommanded to read the chapters **[introducing Woleet API concepts](https://doc.woleet.io/reference)** before reading this documentation. 
 *
 * The version of the OpenAPI document: 1.8.0
 * Contact: contact@woleet.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.woleet.api.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * SignatureRequestDelegate
 */

public class SignatureRequestDelegate {
  public static final String SERIALIZED_NAME_SIGNEE_ID = "signeeId";
  @SerializedName(SERIALIZED_NAME_SIGNEE_ID)
  private String signeeId;

  public static final String SERIALIZED_NAME_O_T_P = "OTP";
  @SerializedName(SERIALIZED_NAME_O_T_P)
  private String OTP;


  public SignatureRequestDelegate signeeId(String signeeId) {
    
    this.signeeId = signeeId;
    return this;
  }

   /**
   * Secret identifier of the signer (provided by email).
   * @return signeeId
  **/
  @ApiModelProperty(required = true, value = "Secret identifier of the signer (provided by email).")

  public String getSigneeId() {
    return signeeId;
  }


  public void setSigneeId(String signeeId) {
    this.signeeId = signeeId;
  }


  public SignatureRequestDelegate OTP(String OTP) {
    
    this.OTP = OTP;
    return this;
  }

   /**
   * OTP of the signer (only required if &#x60;requiresOTP&#x60; was set to &#x60;true&#x60; for thìs signer). 
   * @return OTP
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "OTP of the signer (only required if `requiresOTP` was set to `true` for thìs signer). ")

  public String getOTP() {
    return OTP;
  }


  public void setOTP(String OTP) {
    this.OTP = OTP;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SignatureRequestDelegate signatureRequestDelegate = (SignatureRequestDelegate) o;
    return Objects.equals(this.signeeId, signatureRequestDelegate.signeeId) &&
        Objects.equals(this.OTP, signatureRequestDelegate.OTP);
  }

  @Override
  public int hashCode() {
    return Objects.hash(signeeId, OTP);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SignatureRequestDelegate {\n");
    sb.append("    signeeId: ").append(toIndentedString(signeeId)).append("\n");
    sb.append("    OTP: ").append(toIndentedString(OTP)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

