/*
 * Woleet API
 * Welcome to **Woleet API reference documentation**.<br> It is highly recommanded to read the chapters **[introducing Woleet API concepts](https://doc.woleet.io/v1.5.1/reference)** before reading this documentation. 
 *
 * OpenAPI spec version: 1.5.1
 * Contact: contact@woleet.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.woleet.api.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * SignatureRequestSignResult
 */

public class SignatureRequestSignResult {
  @SerializedName("anchorid")
  private String anchorid = null;

  public SignatureRequestSignResult anchorid(String anchorid) {
    this.anchorid = anchorid;
    return this;
  }

   /**
   * Identifier of the signature anchor created. 
   * @return anchorid
  **/
  @ApiModelProperty(value = "Identifier of the signature anchor created. ")
  public String getAnchorid() {
    return anchorid;
  }

  public void setAnchorid(String anchorid) {
    this.anchorid = anchorid;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SignatureRequestSignResult signatureRequestSignResult = (SignatureRequestSignResult) o;
    return Objects.equals(this.anchorid, signatureRequestSignResult.anchorid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(anchorid);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SignatureRequestSignResult {\n");
    
    sb.append("    anchorid: ").append(toIndentedString(anchorid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

