/*
 * Woleet API
 * Welcome to **Woleet API reference documentation**.<br> It is highly recommanded to read the chapters **[introducing Woleet API concepts](https://doc.woleet.io/reference)** before reading this documentation. 
 *
 * The version of the OpenAPI document: 1.7.5
 * Contact: contact@woleet.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.woleet.api.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * SignatureRequestFeedback
 */

public class SignatureRequestFeedback {
  public static final String SERIALIZED_NAME_SIGNEE_ID = "signeeId";
  @SerializedName(SERIALIZED_NAME_SIGNEE_ID)
  private String signeeId;

  public static final String SERIALIZED_NAME_SUBJECT = "subject";
  @SerializedName(SERIALIZED_NAME_SUBJECT)
  private String subject;

  public static final String SERIALIZED_NAME_MESSAGE = "message";
  @SerializedName(SERIALIZED_NAME_MESSAGE)
  private String message;


  public SignatureRequestFeedback signeeId(String signeeId) {
    
    this.signeeId = signeeId;
    return this;
  }

   /**
   * Secret identifier of the signer (provided by email).
   * @return signeeId
  **/
  @ApiModelProperty(required = true, value = "Secret identifier of the signer (provided by email).")

  public String getSigneeId() {
    return signeeId;
  }


  public void setSigneeId(String signeeId) {
    this.signeeId = signeeId;
  }


  public SignatureRequestFeedback subject(String subject) {
    
    this.subject = subject;
    return this;
  }

   /**
   * Feedback subject to report to the owner of the signature request.
   * @return subject
  **/
  @ApiModelProperty(required = true, value = "Feedback subject to report to the owner of the signature request.")

  public String getSubject() {
    return subject;
  }


  public void setSubject(String subject) {
    this.subject = subject;
  }


  public SignatureRequestFeedback message(String message) {
    
    this.message = message;
    return this;
  }

   /**
   * Feedback message to report to the owner of the signature request.
   * @return message
  **/
  @ApiModelProperty(required = true, value = "Feedback message to report to the owner of the signature request.")

  public String getMessage() {
    return message;
  }


  public void setMessage(String message) {
    this.message = message;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SignatureRequestFeedback signatureRequestFeedback = (SignatureRequestFeedback) o;
    return Objects.equals(this.signeeId, signatureRequestFeedback.signeeId) &&
        Objects.equals(this.subject, signatureRequestFeedback.subject) &&
        Objects.equals(this.message, signatureRequestFeedback.message);
  }

  @Override
  public int hashCode() {
    return Objects.hash(signeeId, subject, message);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SignatureRequestFeedback {\n");
    sb.append("    signeeId: ").append(toIndentedString(signeeId)).append("\n");
    sb.append("    subject: ").append(toIndentedString(subject)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

