/*
 * Woleet API
 * Welcome to **Woleet API reference documentation**.<br> It is highly recommanded to read the chapters **[introducing Woleet API concepts](https://doc.woleet.io/v1.5.1/reference)** before reading this documentation. 
 *
 * OpenAPI spec version: 1.5.1
 * Contact: contact@woleet.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.woleet.api.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * X500Name
 */

public class X500Name {
  @SerializedName("C")
  private String C = null;

  @SerializedName("ST")
  private String ST = null;

  @SerializedName("L")
  private String L = null;

  @SerializedName("O")
  private String O = null;

  @SerializedName("OU")
  private String OU = null;

  @SerializedName("CN")
  private String CN = null;

  public X500Name C(String C) {
    this.C = C;
    return this;
  }

   /**
   * Country/region
   * @return C
  **/
  @ApiModelProperty(value = "Country/region")
  public String getC() {
    return C;
  }

  public void setC(String C) {
    this.C = C;
  }

  public X500Name ST(String ST) {
    this.ST = ST;
    return this;
  }

   /**
   * State or Province
   * @return ST
  **/
  @ApiModelProperty(value = "State or Province")
  public String getST() {
    return ST;
  }

  public void setST(String ST) {
    this.ST = ST;
  }

  public X500Name L(String L) {
    this.L = L;
    return this;
  }

   /**
   * Locality
   * @return L
  **/
  @ApiModelProperty(value = "Locality")
  public String getL() {
    return L;
  }

  public void setL(String L) {
    this.L = L;
  }

  public X500Name O(String O) {
    this.O = O;
    return this;
  }

   /**
   * Organization
   * @return O
  **/
  @ApiModelProperty(value = "Organization")
  public String getO() {
    return O;
  }

  public void setO(String O) {
    this.O = O;
  }

  public X500Name OU(String OU) {
    this.OU = OU;
    return this;
  }

   /**
   * Organizational Unit
   * @return OU
  **/
  @ApiModelProperty(value = "Organizational Unit")
  public String getOU() {
    return OU;
  }

  public void setOU(String OU) {
    this.OU = OU;
  }

  public X500Name CN(String CN) {
    this.CN = CN;
    return this;
  }

   /**
   * Common Name
   * @return CN
  **/
  @ApiModelProperty(value = "Common Name")
  public String getCN() {
    return CN;
  }

  public void setCN(String CN) {
    this.CN = CN;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    X500Name x500Name = (X500Name) o;
    return Objects.equals(this.C, x500Name.C) &&
        Objects.equals(this.ST, x500Name.ST) &&
        Objects.equals(this.L, x500Name.L) &&
        Objects.equals(this.O, x500Name.O) &&
        Objects.equals(this.OU, x500Name.OU) &&
        Objects.equals(this.CN, x500Name.CN);
  }

  @Override
  public int hashCode() {
    return Objects.hash(C, ST, L, O, OU, CN);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class X500Name {\n");
    
    sb.append("    C: ").append(toIndentedString(C)).append("\n");
    sb.append("    ST: ").append(toIndentedString(ST)).append("\n");
    sb.append("    L: ").append(toIndentedString(L)).append("\n");
    sb.append("    O: ").append(toIndentedString(O)).append("\n");
    sb.append("    OU: ").append(toIndentedString(OU)).append("\n");
    sb.append("    CN: ").append(toIndentedString(CN)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

